'use client';

import React from 'react';
import Hero from '@/components/Hero';
import About from '@/components/About';
import Services from '@/components/Services';
import Experience from '@/components/Experience';
import Testimonials from '@/components/Testimonials';
import Booking from '@/components/Booking';
import Location from '@/components/Location';
import CTA from '@/components/CTA';
import Footer from '@/components/Footer';

export default function HomePage() {
  return (
    <>
      <main className="flex-1 container mx-auto px-4 py-8">
        {/* Components generated by the builder will be added here */}
      
        <Hero />
        <About />
        <Services />
        <Experience />
        <Testimonials />
        <Booking />
        <Location />
        <CTA />
        <Footer />
      </main>
    </>
  );
}